// app.js
import {genCardStyle,assortLessons} from './utils/schedule'
import {getCurrentWeek} from './utils/time'

App({
  globalData: {
    termRange:[],
    currentWeek:1
  },
  onLaunch() {
    //获取学期开始和结束日期
    const termRange=[ '2022-08-29', '2023-01-08' ]
    this.globalData.termRange=termRange
    //获取当前周
    this.globalData.currentWeek=getCurrentWeek(termRange[0],termRange[1])
    //
    wx.setStorageSync('experiments', [

      {
        "date": "二○二二年十月二十七日",
        "dateDigit": "2022年10月27日",
        "dateDigitSeparator": "2022-10-27",
        "day": "27",
        "dycdxq": "6号楼313实验室/6号楼313实验室专用/莲花街校区",
        "jgpxzd": "1",
        "jsxm": "赵志鹏",
        "kch": "301041011A",
        "kcmc": "计算机网络",
        "listnav": "false",
        "localeKey": "zh_CN",
        "month": "10",
        "pageTotal": 0,
        "pageable": true,
        "queryModel": {
          "currentPage": 1,
          "currentResult": 0,
          "entityOrField": false,
          "limit": 15,
          "offset": 0,
          "pageNo": 0,
          "pageSize": 15,
          "showCount": 10,
          "sorts": [],
          "totalCount": 0,
          "totalPage": 0,
          "totalResult": 0
        },
        "rangeable": true,
        "row_id": "1",
        "rsdzjs": 0,
        "sksjdd": "星期四 [5-6节 13周] 6号楼313实验室 ",
        "syfzmc": "分组1",
        "totalResult": "20",
        "userModel": {
          "monitor": false,
          "roleCount": 0,
          "roleKeys": "",
          "roleValues": "",
          "status": 0,
          "usable": false
        },
        "xh": "201913040108",
        "xm": "尚益州",
        "xmmc": "网络协议分析",
        "xmz_id": "E835E4A1E36F0B4FE0535FFE12AC7988",
        "xnm": "2022-2023",
        "xqm": "1",
        "year": "2022"
      },
      {
        "date": "二○二二年十月二十七日",
        "dateDigit": "2022年10月27日",
        "dateDigitSeparator": "2022-10-27",
        "day": "27",
        "dycdxq": "6号楼313实验室/6号楼313实验室专用/莲花街校区",
        "jgpxzd": "1",
        "jsxm": "廖天力",
        "kch": "401041003A",
        "kcmc": "计算机图形学",
        "listnav": "false",
        "localeKey": "zh_CN",
        "month": "10",
        "pageTotal": 0,
        "pageable": true,
        "queryModel": {
          "currentPage": 1,
          "currentResult": 0,
          "entityOrField": false,
          "limit": 15,
          "offset": 0,
          "pageNo": 0,
          "pageSize": 15,
          "showCount": 10,
          "sorts": [],
          "totalCount": 0,
          "totalPage": 0,
          "totalResult": 0
        },
        "rangeable": true,
        "row_id": "2",
        "rsdzjs": 0,
        "sksjdd": "星期四 [3-4节 4周] 6号楼313实验室 ",
        "syfzmc": "分组1",
        "totalResult": "20",
        "userModel": {
          "monitor": false,
          "roleCount": 0,
          "roleKeys": "",
          "roleValues": "",
          "status": 0,
          "usable": false
        },
        "xh": "201913040108",
        "xm": "尚益州",
        "xmmc": "计算机绘图基础",
        "xmz_id": "E83FB8B3EAD5B45DE0535FFE12AC1087",
        "xnm": "2022-2023",
        "xqm": "1",
        "year": "2022"
      },
      {
        "date": "二○二二年十月二十七日",
        "dateDigit": "2022年10月27日",
        "dateDigitSeparator": "2022-10-27",
        "day": "27",
        "dycdxq": "6号楼313实验室/6号楼313实验室专用/莲花街校区",
        "jgpxzd": "1",
        "jsxm": "赵志鹏",
        "kch": "301041011A",
        "kcmc": "计算机网络",
        "listnav": "false",
        "localeKey": "zh_CN",
        "month": "10",
        "pageTotal": 0,
        "pageable": true,
        "queryModel": {
          "currentPage": 1,
          "currentResult": 0,
          "entityOrField": false,
          "limit": 15,
          "offset": 0,
          "pageNo": 0,
          "pageSize": 15,
          "showCount": 10,
          "sorts": [],
          "totalCount": 0,
          "totalPage": 0,
          "totalResult": 0
        },
        "rangeable": true,
        "row_id": "3",
        "rsdzjs": 0,
        "sksjdd": "星期二 [3-4节 13周] 6号楼313实验室 ,星期四 [5-6节 12周] 6号楼313实验室 ",
        "syfzmc": "分组1",
        "totalResult": "20",
        "userModel": {
          "monitor": false,
          "roleCount": 0,
          "roleKeys": "",
          "roleValues": "",
          "status": 0,
          "usable": false
        },
        "xh": "201913040108",
        "xm": "尚益州",
        "xmmc": "路由协议的配置",
        "xmz_id": "E836039887DE0BB5E0535FFE12ACAD5E",
        "xnm": "2022-2023",
        "xqm": "1",
        "year": "2022"
      },
      {
        "date": "二○二二年十月二十七日",
        "dateDigit": "2022年10月27日",
        "dateDigitSeparator": "2022-10-27",
        "day": "27",
        "dycdxq": "6号楼313实验室/6号楼313实验室专用/莲花街校区",
        "jgpxzd": "1",
        "jsxm": "董卓莉",
        "kch": "301041013A",
        "kcmc": "软件工程",
        "listnav": "false",
        "localeKey": "zh_CN",
        "month": "10",
        "pageTotal": 0,
        "pageable": true,
        "queryModel": {
          "currentPage": 1,
          "currentResult": 0,
          "entityOrField": false,
          "limit": 15,
          "offset": 0,
          "pageNo": 0,
          "pageSize": 15,
          "showCount": 10,
          "sorts": [],
          "totalCount": 0,
          "totalPage": 0,
          "totalResult": 0
        },
        "rangeable": true,
        "row_id": "4",
        "rsdzjs": 0,
        "sksjdd": "星期四 [3-4节 10周] 6号楼313实验室 ",
        "syfzmc": "分组1",
        "totalResult": "20",
        "userModel": {
          "monitor": false,
          "roleCount": 0,
          "roleKeys": "",
          "roleValues": "",
          "status": 0,
          "usable": false
        },
        "xh": "201913040108",
        "xm": "尚益州",
        "xmmc": "设计建模（二）",
        "xmz_id": "EA82C1D26E59A717E0535FFE12ACD79A",
        "xnm": "2022-2023",
        "xqm": "1",
        "year": "2022"
      },
      {
        "date": "二○二二年十月二十七日",
        "dateDigit": "2022年10月27日",
        "dateDigitSeparator": "2022-10-27",
        "day": "27",
        "dycdxq": "6号楼313实验室/6号楼313实验室专用/莲花街校区",
        "jgpxzd": "1",
        "jsxm": "董卓莉",
        "kch": "301041013A",
        "kcmc": "软件工程",
        "listnav": "false",
        "localeKey": "zh_CN",
        "month": "10",
        "pageTotal": 0,
        "pageable": true,
        "queryModel": {
          "currentPage": 1,
          "currentResult": 0,
          "entityOrField": false,
          "limit": 15,
          "offset": 0,
          "pageNo": 0,
          "pageSize": 15,
          "showCount": 10,
          "sorts": [],
          "totalCount": 0,
          "totalPage": 0,
          "totalResult": 0
        },
        "rangeable": true,
        "row_id": "5",
        "rsdzjs": 0,
        "sksjdd": "星期四 [3-4节 11周] 6号楼313实验室 ",
        "syfzmc": "分组1",
        "totalResult": "20",
        "userModel": {
          "monitor": false,
          "roleCount": 0,
          "roleKeys": "",
          "roleValues": "",
          "status": 0,
          "usable": false
        },
        "xh": "201913040108",
        "xm": "尚益州",
        "xmmc": "设计建模（三）",
        "xmz_id": "EA82A7A6066AA4D0E0535FFE12AC5A68",
        "xnm": "2022-2023",
        "xqm": "1",
        "year": "2022"
      },
      {
        "date": "二○二二年十月二十七日",
        "dateDigit": "2022年10月27日",
        "dateDigitSeparator": "2022-10-27",
        "day": "27",
        "dycdxq": "6号楼313实验室/6号楼313实验室专用/莲花街校区",
        "jgpxzd": "1",
        "jsxm": "董卓莉",
        "kch": "301041013A",
        "kcmc": "软件工程",
        "listnav": "false",
        "localeKey": "zh_CN",
        "month": "10",
        "pageTotal": 0,
        "pageable": true,
        "queryModel": {
          "currentPage": 1,
          "currentResult": 0,
          "entityOrField": false,
          "limit": 15,
          "offset": 0,
          "pageNo": 0,
          "pageSize": 15,
          "showCount": 10,
          "sorts": [],
          "totalCount": 0,
          "totalPage": 0,
          "totalResult": 0
        },
        "rangeable": true,
        "row_id": "6",
        "rsdzjs": 0,
        "sksjdd": "星期四 [3-4节 9周] 6号楼313实验室 ",
        "syfzmc": "分组1",
        "totalResult": "20",
        "userModel": {
          "monitor": false,
          "roleCount": 0,
          "roleKeys": "",
          "roleValues": "",
          "status": 0,
          "usable": false
        },
        "xh": "201913040108",
        "xm": "尚益州",
        "xmmc": "设计建模（一）",
        "xmz_id": "EA82C1D26DE7A717E0535FFE12ACD79A",
        "xnm": "2022-2023",
        "xqm": "1",
        "year": "2022"
      },
      {
        "date": "二○二二年十月二十七日",
        "dateDigit": "2022年10月27日",
        "dateDigitSeparator": "2022-10-27",
        "day": "27",
        "dycdxq": "6号楼313实验室/6号楼313实验室专用/莲花街校区",
        "jgpxzd": "1",
        "jsxm": "赵志鹏",
        "kch": "301041011A",
        "kcmc": "计算机网络",
        "listnav": "false",
        "localeKey": "zh_CN",
        "month": "10",
        "pageTotal": 0,
        "pageable": true,
        "queryModel": {
          "currentPage": 1,
          "currentResult": 0,
          "entityOrField": false,
          "limit": 15,
          "offset": 0,
          "pageNo": 0,
          "pageSize": 15,
          "showCount": 10,
          "sorts": [],
          "totalCount": 0,
          "totalPage": 0,
          "totalResult": 0
        },
        "rangeable": true,
        "row_id": "7",
        "rsdzjs": 0,
        "sksjdd": "星期二 [3-4节 12周] 6号楼313实验室 ",
        "syfzmc": "分组1",
        "totalResult": "20",
        "userModel": {
          "monitor": false,
          "roleCount": 0,
          "roleKeys": "",
          "roleValues": "",
          "status": 0,
          "usable": false
        },
        "xh": "201913040108",
        "xm": "尚益州",
        "xmmc": "网络命令的使用",
        "xmz_id": "E8355ED4A7610101E0535FFE12AC3BF1",
        "xnm": "2022-2023",
        "xqm": "1",
        "year": "2022"
      },
      {
        "date": "二○二二年十月二十七日",
        "dateDigit": "2022年10月27日",
        "dateDigitSeparator": "2022-10-27",
        "day": "27",
        "dycdxq": "6号楼313实验室/6号楼313实验室专用/莲花街校区",
        "jgpxzd": "1",
        "jsxm": "董卓莉",
        "kch": "301041013A",
        "kcmc": "软件工程",
        "listnav": "false",
        "localeKey": "zh_CN",
        "month": "10",
        "pageTotal": 0,
        "pageable": true,
        "queryModel": {
          "currentPage": 1,
          "currentResult": 0,
          "entityOrField": false,
          "limit": 15,
          "offset": 0,
          "pageNo": 0,
          "pageSize": 15,
          "showCount": 10,
          "sorts": [],
          "totalCount": 0,
          "totalPage": 0,
          "totalResult": 0
        },
        "rangeable": true,
        "row_id": "8",
        "rsdzjs": 0,
        "sksjdd": "星期四 [3-4节 8周] 6号楼313实验室 ",
        "syfzmc": "分组1",
        "totalResult": "20",
        "userModel": {
          "monitor": false,
          "roleCount": 0,
          "roleKeys": "",
          "roleValues": "",
          "status": 0,
          "usable": false
        },
        "xh": "201913040108",
        "xm": "尚益州",
        "xmmc": "需求建模（二）",
        "xmz_id": "EA82C1D26CFEA717E0535FFE12ACD79A",
        "xnm": "2022-2023",
        "xqm": "1",
        "year": "2022"
      },
      {
        "date": "二○二二年十月二十七日",
        "dateDigit": "2022年10月27日",
        "dateDigitSeparator": "2022-10-27",
        "day": "27",
        "dycdxq": "6号楼313实验室/6号楼313实验室专用/莲花街校区",
        "jgpxzd": "1",
        "jsxm": "董卓莉",
        "kch": "301041013A",
        "kcmc": "软件工程",
        "listnav": "false",
        "localeKey": "zh_CN",
        "month": "10",
        "pageTotal": 0,
        "pageable": true,
        "queryModel": {
          "currentPage": 1,
          "currentResult": 0,
          "entityOrField": false,
          "limit": 15,
          "offset": 0,
          "pageNo": 0,
          "pageSize": 15,
          "showCount": 10,
          "sorts": [],
          "totalCount": 0,
          "totalPage": 0,
          "totalResult": 0
        },
        "rangeable": true,
        "row_id": "9",
        "rsdzjs": 0,
        "sksjdd": "星期四 [3-4节 7周] 6号楼313实验室 ",
        "syfzmc": "分组1",
        "totalResult": "20",
        "userModel": {
          "monitor": false,
          "roleCount": 0,
          "roleKeys": "",
          "roleValues": "",
          "status": 0,
          "usable": false
        },
        "xh": "201913040108",
        "xm": "尚益州",
        "xmmc": "需求建模（一）",
        "xmz_id": "EA8248EB84ED9EE6E0535FFE12AC0AB1",
        "xnm": "2022-2023",
        "xqm": "1",
        "year": "2022"
      },
      {
        "date": "二○二二年十月二十七日",
        "dateDigit": "2022年10月27日",
        "dateDigitSeparator": "2022-10-27",
        "day": "27",
        "dycdxq": "6号楼321实验室/6号楼321实验室专用/莲花街校区",
        "jgpxzd": "1",
        "jsxm": "王洪群",
        "kch": "401041004A",
        "kcmc": "嵌入式操作系统",
        "listnav": "false",
        "localeKey": "zh_CN",
        "month": "10",
        "pageTotal": 0,
        "pageable": true,
        "queryModel": {
          "currentPage": 1,
          "currentResult": 0,
          "entityOrField": false,
          "limit": 15,
          "offset": 0,
          "pageNo": 0,
          "pageSize": 15,
          "showCount": 10,
          "sorts": [],
          "totalCount": 0,
          "totalPage": 0,
          "totalResult": 0
        },
        "rangeable": true,
        "row_id": "10",
        "rsdzjs": 0,
        "sksjdd": "星期四 [11-12节 8周] 6号楼321实验室 ",
        "syfzmc": "分组2",
        "totalResult": "20",
        "userModel": {
          "monitor": false,
          "roleCount": 0,
          "roleKeys": "",
          "roleValues": "",
          "status": 0,
          "usable": false
        },
        "xh": "201913040108",
        "xm": "尚益州",
        "xmmc": "ADS的安装与使用",
        "xmz_id": "E84B98F125F04841E0535FFE12AC9918",
        "xnm": "2022-2023",
        "xqm": "1",
        "year": "2022"
      }

    ])
    const lessons=[
        {
          name: '计算机图形学',
          teacher_name: '廖天力',
          classroom: '文科组团楼311',
          time: '1-2节',
          credit: '2.5',
          dayOfWeek: '1',
          timeRange: [ 1, 2 ],
          weekRange: [ 1, 7 ]
        },
        {
          name: '数据库系统原理及应用',
          teacher_name: '张春燕',
          classroom: '莲4号教学楼513',
          time: '3-4节',
          credit: '3.5',
          dayOfWeek: '1',
          timeRange: [ 3, 4 ],
          weekRange: [ 1, 11 ]
        },
        {
          name: '微机原理及接口技术',
          teacher_name: '吕鹏涛',
          classroom: '莲4号教学楼532',
          time: '5-6节',
          credit: '3.5',
          dayOfWeek: '1',
          timeRange: [ 5, 6 ],
          weekRange: [ 1, 12 ]
        },
        {
          name: '嵌入式操作系统',
          teacher_name: '王洪群',
          classroom: '莲4号教学楼322',
          time: '9-10节',
          credit: '2.5',
          dayOfWeek: '1',
          timeRange: [ 9, 10 ],
          weekRange: [ 7, 13 ]
        },
        {
          name: '软件工程',
          teacher_name: '李磊x',
          classroom: '文科组团楼310',
          time: '1-2节',
          credit: '3.0',
          dayOfWeek: '2',
          timeRange: [ 1, 2 ],
          weekRange: [ 1, 11 ]
        },
        {
          name: '计算机网络',
          teacher_name: '赵志鹏',
          classroom: '莲4号教学楼513',
          time: '3-4节',
          credit: '3.0',
          dayOfWeek: '2',
          timeRange: [ 3, 4 ],
          weekRange: [ 1, 11 ]
        },
        {
          name: '微机原理及接口技术',
          teacher_name: '吕鹏涛',
          classroom: '莲4号教学楼531',
          time: '1-2节',
          credit: '3.5',
          dayOfWeek: '3',
          timeRange: [ 1, 2 ],
          weekRange: [ 1, 12 ]
        },
        {
          name: '数据库系统原理及应用',
          teacher_name: '张春燕',
          classroom: '莲4号教学楼513',
          time: '5-6节',
          credit: '3.5',
          dayOfWeek: '3',
          timeRange: [ 5, 6 ],
          weekRange: [ 1, 11 ]
        },
        {
          name: '习近平新时代中国特色社会主义思想概论',
          teacher_name: '赵排风',
          classroom: '莲4号教学楼340',
          time: '7-8节',
          credit: '3.0',
          dayOfWeek: '3',
          timeRange: [ 7, 8 ],
          weekRange: [ 8, 14 ]
        },
        {
          name: '软件工程',
          teacher_name: '李磊x',
          classroom: '文科组团楼310',
          time: '1-2节',
          credit: '3.0',
          dayOfWeek: '4',
          timeRange: [ 1, 2 ],
          weekRange: [ 1, 11 ]
        },
        {
          name: '计算机网络',
          teacher_name: '赵志鹏',
          classroom: '莲4号教学楼413',
          time: '5-6节',
          credit: '3.0',
          dayOfWeek: '4',
          timeRange: [ 5, 6 ],
          weekRange: [ 1, 11 ]
        },
        {
          name: '习近平新时代中国特色社会主义思想概论',
          teacher_name: '赵排风',
          classroom: '文科组团楼310',
          time: '7-8节',
          credit: '3.0',
          dayOfWeek: '4',
          timeRange: [ 7, 8 ],
          weekRange: [ 1, 14 ]
        },
        {
          name: '形势与政策(五)',
          teacher_name: '赵排风',
          classroom: '莲4号教学楼406',
          time: '3-4节',
          credit: '0.25',
          dayOfWeek: '5',
          timeRange: [ 3, 4 ],
          weekRange: [ 4, 7 ]
        },
        {
          name: '嵌入式操作系统',
          teacher_name: '王洪群',
          classroom: '莲4号教学楼322',
          time: '5-6节',
          credit: '2.5',
          dayOfWeek: '5',
          timeRange: [ 5, 6 ],
          weekRange: [ 7, 14 ]
        },
        {
          name: '计算机图形学',
          teacher_name: '廖天力',
          classroom: '文科组团楼311',
          time: '3-4节',
          credit: '2.5',
          dayOfWeek: '6',
          timeRange: [ 3, 4 ],
          weekRange: [ 1, 6 ]
        }
    ]
    this.globalData.lessons = assortLessons(termRange,genCardStyle(lessons))
    // this.globalData.experiments = wx.getStorageSync('experiments')
    console.log(this.globalData.lessons);
    wx.setStorageSync('lessons',this.globalData.lessons)
    
    //profile
    const profile=wx.getStorageSync('profile')
    if(!profile.name){
        //如果没有获取教务系统
        wx.setStorageSync('profile', {
            xh:201911020101,
            name:"闻苏鹏",
            class:"计科2005",
            college:"信息科学与工程学院"
        })
    }
    this.globalData.profile=wx.getStorageSync('profile')


    // 登录
    wx.login({
      success: res => {
        // 发送 res.code 到后台换取 openId, sessionKey, unionId
      }
    })
  },
})
